title: "ERSSTv5"
description: "Extended Reconstructed Sea Surface Temperature version 5"
recipes:
  - id: "default"
    object: "recipe:default"
provenance:
  providers:
    - name: "NOAA PSL"
      description: "NOAA Physical Sciences Laboratory"
      roles:
        - producer
        - licensor
  license: "No Usage Restrictions"
maintainers:
  - name: "Sungjoon Park"
    orcid: "0000-0000-0000-0000"
    github: sungjoon0710
